default_session = "main"
bookmarks = [
    "~/dotfiles",
    "~/code",
    "~/Downloads",
    "~/Documents",
    "~/Pictures",
    "~/Music",
    "~/Videos",
    "~/Desktop",
    "~/Obsidian",
    "~/VMs",
    "~/code/cybersec"
]

[[search_dirs]]
path = "~/code"
depth = 1
