default_session = "main"
bookmarks = [
    "~/dotfiles",
    "~/Downloads",
    "~/Documents",
    "~/Pictures",
    "~/Music",
    "~/Videos",
    "~/Desktop",
    "~/Obsidian",
    "~/VMs",
    "~/code/random-tests",
    "~/code/cybersec",
]

[[search_dirs]]
path = "~/code"
depth = 1
